### ISSUE TITLE
Configure Sonar Quality Analysis

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-sequelize#18]
**Describe the bug**
Sonar analysis on PR and master branch is missing.
Needs to added soon

**Comment by shubhamp-sf** [comment]
@yeshamavani this repo is gonna be archived in favour of it's merger in loopback-next repo.
Will add sonar if we continue to maintain it here as well.

**Comment by shubhamp-sf** [comment]
Closing as this is to be archived this month.
