### ISSUE TITLE
Provision for query logs 

### ISSUE THREAD

**Issue by subhamjagurisf** [sourcefuse/loopback4-sequelize#31]
**Is your feature request related to a problem? Please describe.**
There are many cases where we want to see queries which are actually getting executed when there is any database operation.
In loopback juggler we can use `DEBUG=loopback:connector:postgresql`

It would be great of there is any provision for doing so.

**Comment by shubhamp-sf** [comment]
It's already there @subhamjagurisf. The debug string is named as `loopback:sequelize:queries`.

Documented here: https://github.com/sourcefuse/loopback4-sequelize#debug-strings-reference

PS: Please use the official version of this package: https://www.npmjs.com/package/@loopback/sequelize as we'll be deprecating loopback4-sequelize soon and upcoming updates will be published on the `@loopback/sequelize` only.
