### ISSUE TITLE
Usage with a case-sensitive database leads to query “table not found” errors

### ISSUE THREAD

**Issue by KalleV** [sourcefuse/loopback4-sequelize#34]
Great project! Almost a seamless replacement for the loopback juggler. I wasn’t sure if I should post issues here or in the loopback-next repository given the deprecation notice.

**Describe the bug**
I came across an edge case. The lower cased table name here leads to a “breaking change” for projects relying on the table name matching the casing of the entity definition:
https://github.com/sourcefuse/loopback4-sequelize/blob/a6aaaf0ba8f09dc39c1d9ea38a23797f4f117d19/src/sequelize/sequelize.repository.base.ts#L635

**To Reproduce**

1. Set up a MySQL database with case-sensitive table names (https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names)
2. Create a new entity (eg “class Book”)
3. Use a repository operation (eg find)
4. Query errors with table “book” not found.

**Expected behavior**
Successful query using “Book” as the table name.

**Comment by shubhamp-sf** [comment]
It isn't necessarily going to be breaking if users define the name they want in the model definition.

**Comment by shubhamp-sf** [comment]
Will post a solution soon.

**Comment by KalleV** [comment]
🎉 I tested your update and it worked. Thank you!

**Comment by shubhamp-sf** [comment]
Closed by https://github.com/loopbackio/loopback-next/pull/9581
