### ISSUE TITLE
@belongsTo with a default “keyTo” leads to a broken relation query

### ISSUE THREAD

**Issue by KalleV** [sourcefuse/loopback4-sequelize#35]
**Describe the bug**
The belongsTo relation mapping from Loopback 4 to Sequelize has an edge case when using the default “keyTo” option.

References:
https://loopback.io/doc/en/lb4/BelongsTo-relation.html#relation-metadata

**To Reproduce**

1. Create 2 Loopback entities (eg Book and Reader)
2. Create a belongsTo relation in one of them such as:
```
@belongsTo(() => Reader, null, {
    type: 'string',
    required: false,
    length: 500
  })
  public readerId: string;
```
4. Set the 2nd decorator argument to “null” or undefined
5. Try to query the relation
6. Observe a broken query to the relation (when using the DEBUG env variable) containing something like “readerreaderId”.

**Expected behavior**
Successful query when using the default options generated by Loopback for a belongsTo relation.

**Additional context**
I haven’t confirmed it but I assume the code in this section might need an update: https://github.com/sourcefuse/loopback4-sequelize/blob/a6aaaf0ba8f09dc39c1d9ea38a23797f4f117d19/src/sequelize/sequelize.repository.base.ts#L658 

Quick workaround is to explicitly set the “{ keyTo }” in the decorator options.

**Comment by KalleV** [comment]
I did some more investigation on this one and found this in the documentation for the default foreign key set by Sequelize:
https://sequelize.org/api/v6/class/src/model.js~model#static-method-belongsTo

> The name of the foreign key attribute in the source table or an object representing the type definition for the foreign column (see Sequelize.define for syntax). When using an object, you can add a name property to set the name of the column. Defaults to the name of target + primary key of target

**Comment by RaghavaroraSF** [comment]
Hii @KalleV 
I have checked it via postgresql and mysql and it is showing correct data this is the resulting query
[
![Screenshot from 2023-06-06 20-04-19](https://github.com/sourcefuse/loopback4-sequelize/assets/97958393/92bed344-6c69-4eb6-aa25-1b1d3b0ec12a)

**Comment by KalleV** [comment]
Ok looks like it wasn't quite that simple to replicate in isolation. To replicate it with minimal code, I had to introduce another belongsTo relation in another entity in addition to leaving out the relation keys in the decorator: https://github.com/KalleV/loopback-next/commit/3c29d852b46f19f4805d556ae32aee49c79471f1
