### ISSUE TITLE
Regression in Entity "hiddenProperty" behavior when creating a new entity via SequelizeCrudRepository#create

### ISSUE THREAD

**Issue by KalleV** [sourcefuse/loopback4-sequelize#37]
**Describe the bug**
I noticed that Entity properties marked as hidden are not accessible immediately after creation using a repository extending the `SequelizeCrudRepository`.

I traced it to this code:
 - https://github.com/sourcefuse/loopback4-sequelize/blob/1de33ea013e6b04663d0e08535ae236c3984641f/src/sequelize/sequelize.repository.base.ts#L132
 - https://github.com/sourcefuse/loopback4-sequelize/blob/1de33ea013e6b04663d0e08535ae236c3984641f/src/sequelize/sequelize.repository.base.ts#L888

**To Reproduce**

1. Create a new entity with a hidden field (e.g. Book with a decorator like "@model( { hiddenProperties: [ 'theEnding' ] } )") using `Repository.create()`
2. Try to access the hidden property in the backend code
3. Error: "Property is undefined"

**Expected behavior**
Hidden properties should be excluded from the REST API responses but still be accessible in the backend.

**Additional context**
It seems to be related to this PR: https://github.com/sourcefuse/loopback4-sequelize/commit/3e254fd48a307c18e8ede54ce01c87804d29fbe0

My understanding is that Loopback will call "toJSON" when serializing the response which should already handle excluding the hidden properties: https://github.com/loopbackio/loopback-next/blob/057150d78908045c3ac2405b0ba2aac65eb17416/packages/repository/src/model.ts#L341-L370

It seems like changing this line:
https://github.com/sourcefuse/loopback4-sequelize/blob/1de33ea013e6b04663d0e08535ae236c3984641f/src/sequelize/sequelize.repository.base.ts#L132
to the following might be all it takes:
```ts
return new this.entityClass(data.toJSON()) as T;
```

**Comment by shubhamp-sf** [comment]
> Loopback will call "toJSON" when serializing the response which should already handle excluding the hidden properties

It does but the model in this case will be sequelize model which doesn't inherit the loopback's model so a way to replicate similar behaviour for sequelize's model class would help. Will se what can be the done for this.


PS: Thanks so much for testing things out for this package. I would appreciate if you could post future issues on [loopback-next](https://github.com/loopbackio/loopback-next/issues/new/choose) as It's easier for me to point these issue in fix PRs.

**Comment by KalleV** [comment]
No problem! I'm eager to get this working. I'll post issues in Loopback Next instead going forward.
